casa(britanico, roja)
casa(noruego, primera)
casa(C, verde)
casa(A, amarilla)
casa(B, G)
casa(L, centro)
casaalado()
bebe(danes, te)
bebe(C, cafe)
bebe(L, leche)
bebe(DSF, cerveza)
fuma(aleman, prince)
fuma(B, blend)
fuma(AL, blends)
fuma(DSF, bluemaster)
mascota(sueco, perro)
mascota(A, dunhill)
mascota(FD, caballo)